using BibTeXManager.Importing;
using BibTeXManager.Project;
using BibTeXManagerUnitTests;
using DigitalProduction.Http;

namespace BibTeXManagerUnitTests;

public class BulkImportTests
{

	private readonly string[]        _bibEntryStrings        =
	[
		"@proceedings{\r\n\t\t\t\t10.2118/217965-MS,\r\n    author = {Dunn, Joel},\r\n    title = \"{Identifying Cumulative TVD Error in Horizontal Wells Drilled with Rotary Steerable Systems}\",\r\n    volume = {Day 1 Tue, March 05, 2024},\r\n    series = {SPE/IADC Drilling Conference and Exhibition},\r\n    pages = {D011S001R001},\r\n    year = {2024},\r\n    month = {03},\r\n    abstract = \"{It is known that the Stockhausen Effect, characterized as the accumulation of TVD error in directional wellbores resulting from the slide/rotate process employed with bent-housing mud motors, can have a significant impact on wellbore placement in the TVD plane. While much research has been conducted, and commercial solutions have been deployed to account for and correct these errors, all are focused on mud motor slide/rotate drilling. As contemporary drilling programs move to ever-increasing lateral lengths, utilization of Rotary Steerable Systems (RSS) is also trending upward. While potential advantages may exist in favor of RSS, like the elimination of slide drilling, it is important to consider that not all undesirable phenomena associated with slide drilling (well placement error, tortuosity, rugosity, high localized DLS, etc.) vanish from the wellbore. These characteristics are still present in the RSS wellbore and should be analyzed and quantified to ensure that wellbore quality metrics are consistent for all drilling methods.To investigate cumulative TVD error in RSS wells, we developed a system to utilize the real time downhole steering data from RSS to populate a steering sheet that can be processed through an algorithm designed to account for TVD errors resulting from the Stockhausen effect. By capturing the RSS toolface and steering proportion in real time, we can determine at what intervals the RSS is actively steering and during what intervals it is drilling in a neutral, non-biasing mode. The result of cycling between steering and non-steering cycles creates a pattern similar to a slide/rotate sequence experienced when using steerable mud motors. This information allows us to construct a more accurate representation of the true trajectory of the wellbore than is provided by minimum curvature between the standard 95’ survey course lengths. In addition to uncovering TVD error this method also provides a higher resolution picture of various tortuosity metrics like borehole curvature and torsion.We examined data from numerous wells across several basins to observe the TVD error generated by RSS steering mechanisms. It was concluded that these TVD errors should be considered for accurate wellbore positioning, and in addition revealed potential to enhance trajectory optimization capabilities of some Rotary Steerable Systems. In addition to uncovering TVD error, the high-resolution trajectory allows for a thorough examination of wellbore tortuosity, including localized DLS, and wellbore curvature and torsion to aid in identifying potential trouble zones in the lateral.}\",\r\n    doi = {10.2118/217965-MS},\r\n    url = {https://doi.org/10.2118/217965-MS},\r\n    eprint = {https://onepetro.org/SPEDC/proceedings-pdf/24DC/1-24DC/D011S001R001/3381048/spe-217965-ms.pdf},\r\n}",
		"@proceedings{10.2118/217661-MS,\r\n\tauthor\t\t\t= {Cockburn, C. B. and Huseynzade, N. and Rasul-zada, A.},\r\n\ttitle\t\t\t= {{Improving Casing Running Efficiency through a Comprehensive Wellbore Quality Scorecard: A Data-Driven Approach}},\r\n\tvolume\t\t\t= {Day 1 Tue, March 05, 2024},\r\n\tseries\t\t\t= {SPE/IADC Drilling Conference and Exhibition},\r\n\tpages\t\t\t= {D011S001R003},\r\n\tyear\t\t\t= {2024},\r\n\tmonth\t\t\t= {03},\r\n\tabstract\t\t= {{This paper presents the successful development and implementation of a wellbore quality scorecard which is used to evaluate wellbore quality using deterministic and probabilistic methods. This evaluation is based on analysing the real time data during the final trip out of hole with the drilling BHA.The Wellbore Quality Scorecard is being used systematically across a large multi-asset drilling project where there was a history of problematic hole sections. Casing and liner running operations frequently encountered difficulties, and it was recognised that a system for evaluating the hole condition would help to improve operational decision making. The result of the evaluation is used to provide a better understanding of the condition of the wellbore that was drilled before committing to run casing or liner. Understanding the wellbore condition helps the team to decide, for example, whether to run a wiper trip to condition the wellbore or to save time and go ahead with casing or liner run.The evaluation process is a collaboration between the remote collaboration centre, the rigsite team and the office-based operations team. A database is generated which records historical wellbore condition vs liner and casing running information which holds very useful technical insights about how each wellbore parameter quantitatively affects the wellbore quality.The paper will describe how this process has now been applied to over 50 hole sections, and how it has improved decision making and the liner and casing running success rate.A machine learning model has been developed which predicts the likelihood of successfully running the casing or liner to the target depth. This information is used to compliment the Wellbore Quality Score for informing operational decisions.}},\r\n\tdoi\t\t\t\t= {10.2118/217661-MS},\r\n\turl\t\t\t\t= {https://doi.org/10.2118/217661-MS},\r\n\teprint\t\t\t= {https://onepetro.org/SPEDC/proceedings-pdf/24DC/1-24DC/D011S001R003/3379747/spe-217661-ms.pdf}\r\n}",
		"@proceedings{10.2118/217951-MS,\r\n    author = {Brockhoff, J. and Taylor, M. and Dubberley, S. and Ma, K. and Jaska, C.},\r\n    title = \"{Mechanistic Study and Chemical Design of a New Lubricant for High Salinity Drilling Fluids}\",\r\n    volume = {Day 1 Tue, March 05, 2024},\r\n    series = {SPE/IADC Drilling Conference and Exhibition},\r\n    pages = {D012S002R005},\r\n    year = {2024},\r\n    month = {03},\r\n    abstract = \"{The drive to reduce freshwater consumption has led to a significant increase in the use of waste streams, such as high salinity produced water brines, as base fluids in drilling fluid systems. However, the performance of conventional lubricants is typically reduced in such brines. This paper describes the design and development of a new class of lubricant specifically designed for use in high salinity water-based drilling fluids.A comprehensive literature review and a detailed laboratory testing program were undertaken to investigate the mechanism of drilling fluid lubricants under downhole conditions. The knowledge gained from this study was used to design a new class of lubricant that undergoes a chemical reaction with high salinity brines in order to activate the lubricant species and maximize performance.A series of field trials were conducted on wells targeting the Montney formation in Western Canada. The drilling fluids consisted of solids-free sodium chloride, calcium chloride, and produced water brines with densities ranging from 1080 – 1330 kg/m3. The wells had lateral lengths ranging from 1580 – 4000 meters. The new lubricant significantly out-performed conventional lubricants on 100\\\\% of the field trials and was able to achieve friction factors close to those of oil-based drilling fluids. A series of in-depth case studies are provided which highlight the unique performance characteristics of this novel drilling fluid lubricant.}\",\r\n    doi = {10.2118/217951-MS},\r\n    url = {https://doi.org/10.2118/217951-MS},\r\n    eprint = {https://onepetro.org/SPEDC/proceedings-pdf/24DC/1-24DC/D012S002R005/3380921/spe-217951-ms.pdf},\r\n}"
	];

	public BulkImportTests()
	{
		CustomSearchKey? customSearchKey = CustomSearchKey.Deserialize(@"..\..\..\customsearchkey.xml");
		Assert.NotNull(customSearchKey);
		CustomSearch.SetCxAndKey(customSearchKey);
	}

	/// <summary>
	/// 
	/// </summary>
	[Fact]
	public void ImportPredefinedBibtexItems()
	{
		TestBulkImporter importer = new()
		{
			BibEntryStrings = _bibEntryStrings
		};

		string bibEntriesString = "";
		foreach (ImportResult result in importer.BulkImport())
		{
			bibEntriesString += result.BibEntry?.ToString() + Environment.NewLine + Environment.NewLine;
		}
	}

	[Fact]
	public void ImportErrorsTests()
	{
		ErrorsBulkImporter importer = new();

		int attempts = 0;
		int successful = 0;
		int notfound = 0;
		int errors = 0;

		foreach (ImportResult importResult in importer.BulkImport())
		{
			attempts++;
			switch (importResult.Result)
			{
				case ResultType.Successful:
					successful++;
					break;

				case ResultType.NotFound:
					notfound++;
					importer.Continue = ImportErrorHandlingType.Skip;
					break;

				case ResultType.Error:
					errors++;
					importer.Continue = ImportErrorHandlingType.TryAgain;
					break;
			}
		}

		Assert.Equal(attempts, successful+notfound+errors);
		Assert.Equal(2, successful);
	}

} // End class.